name: profiler
description: A tool to profile your application.
version: 1.0.0
homepage: https://github.com/jcowgar/profile

environment:
  sdk: ">=2.7.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
